"""Universe + holdings parsing (Fidelity CSV quirks, plain lists, % vs fraction)."""

from __future__ import annotations

from momentum.holdings import load_holdings
from momentum.universe import load_tickers


def test_load_plain_ticker_list(tmp_path):
    p = tmp_path / "u.txt"
    p.write_text("# comment\nAAPL\nmsft\nBRK.B\n\n123BAD\n")
    assert load_tickers(p) == ["AAPL", "MSFT", "BRK.B"]


def test_load_fidelity_style_csv(tmp_path):
    p = tmp_path / "u.csv"
    p.write_text("Symbol,Company Name,Security Price\nNVDA,Nvidia,900\nXOM,Exxon,110\n")
    assert load_tickers(p) == ["NVDA", "XOM"]


def test_load_csv_with_preamble(tmp_path):
    p = tmp_path / "u.csv"
    p.write_text("Screener export 2025\nGenerated by Fidelity\nSymbol,Price\nWMT,70\nKO,60\n")
    assert load_tickers(p) == ["WMT", "KO"]


def test_dedup_preserves_order(tmp_path):
    p = tmp_path / "u.txt"
    p.write_text("AAPL\nMSFT\nAAPL\n")
    assert load_tickers(p) == ["AAPL", "MSFT"]


def test_holdings_percent_weight_scaled(tmp_path):
    p = tmp_path / "h.csv"
    p.write_text("Symbol,Weight,Current Value\nAAPL,2.5%,2500\nBIL,87.5%,87500\n")
    h = load_holdings(p)
    assert set(h["ticker"]) == {"AAPL", "BIL"}
    aapl = h[h["ticker"] == "AAPL"].iloc[0]
    assert abs(aapl["weight"] - 0.025) < 1e-9      # 2.5% -> 0.025
    assert aapl["value"] == 2500


def test_holdings_fraction_weight_unchanged(tmp_path):
    p = tmp_path / "h.csv"
    p.write_text("Ticker,Weight\nAAPL,0.5\nMSFT,0.5\n")
    h = load_holdings(p)
    assert abs(h[h["ticker"] == "AAPL"].iloc[0]["weight"] - 0.5) < 1e-9
